version: "3.8"

services:
  jupyter:
    container_name: notebooks
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./notebooks:/notebooks
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888